### ISSUE TITLE
More usage examples.

### ISSUE THREAD

**Issue by jaybinks** [TickLabVN/tonic#1]
Can you please provide examples of how to create tonic.RouteSchema{} objects with Params ?

In general, it would be great if there were a few more examples provided.

**Comment by jaybinks** [comment]
Silly me...  you had part of it in your example.
Params expects a Struct :/ 

`			Schema: &tonic.RouteSchema{

				Params: ArticleDTO{},
				//Description: "",
				Response: map[int]interface{}{
					200: []string{},
					503: []string{},
				},
			},`

**Comment by jaybinks** [comment]
On further investigation , the above code shows the correct fields in the Parameter section on swagger docs.
however when executing the example, the data is never sent to the API Server.
(seen in wireshark and dev tools)

Body & QueryString works as expected with the data fields,
however Params dosnt send any data in the POST.

**Comment by phucvinh57** [comment]
Hi @jaybinks,

The version on `master` branch was deprecated. My team decided to develop more so sophisticate version, currently is working on the branch [`v3.1.0`](https://github.com/TickLabVN/tonic/tree/v3.1.0).

Thank you.
